# Generated by Django 5.0.6 on 2024-07-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_rename_name_todolist_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='title',
            new_name='list_name',
        ),
    ]
